"""Generates the Jython script-library code shipped inside the project zip."""

INIT_PY = '''"""flintium - shared helpers for the Flintium Perspective project."""
'''

TOOLS_PY = '''"""flintium.tools - Ignition-flavored MCP tool helpers.

These mirror the in-browser MCP tools shipped in the Flintium GitHub Pages
TAG.DB v2 console, but call the real `system.*` namespaces. They are designed
to be invoked from Perspective bindings, gateway scripts, or the script
console.
"""

# UDT registry baked from pages/data/udts/index.json. Regenerated by the build
# script; do not hand-edit.

UDT_INDEX = {udt_index!r}

INSTANCE_INDEX = {instance_index!r}

TROUBLESHOOT_KB = {{
    "tag not updating": "Check OPC connection, PLC mode (RUN), scan class rate, subscription lease.",
    "quality bad": "Check PLC online, tag path, data type match, system.opc.browseServer().",
    "comm failure": "Check IP, port, PLC RUN mode, rack/slot, driver settings.",
    "gateway connection": "Check network, ports 8088/8043, firewall, gateway.log, redundancy.",
    "alarm flood": "Check setpoints, deadband, shelving. ISA-18.2: <6 alarms/operator/hour.",
    "session timeout": "Check project timeout, auth source, IdP config, session keepalive.",
    "script error": "Check scope (gateway vs client vs session), imports, type coercion, system.util.getLogger.",
    "history gaps": "Check historian config, DB connection, disk space, tag group rate.",
}}


def list_udts():
    """Return UDT type definitions as a Perspective-friendly dataset."""
    return UDT_INDEX


def list_instances():
    """Return seed instance presets as a Perspective-friendly dataset."""
    return INSTANCE_INDEX


def udt_detail(name):
    """Return field metadata for one UDT type."""
    for udt in UDT_INDEX:
        if udt["name"] == name:
            return udt
    return None


def tag_read(path):
    """Read a tag value via system.tag.readBlocking."""
    qv = system.tag.readBlocking([path])[0]
    return {{"value": qv.value, "quality": qv.quality.toString(), "timestamp": qv.timestamp}}


def tag_write(path, value):
    """Write a value to a tag via system.tag.writeBlocking."""
    return system.tag.writeBlocking([path], [value])[0].toString()


def tag_browse(path):
    """Browse children of a tag path using system.tag.browse."""
    results = system.tag.browse(path).results
    return [str(r.fullPath) for r in results]


def tag_history(path, hours=1):
    """Query tag history for the last N hours."""
    end = system.date.now()
    start = system.date.addHours(end, -hours)
    return system.tag.queryTagHistory(paths=[path], startDate=start, endDate=end)


def create_instance(path, udt_type):
    """Create a UDT instance at `path` using a typeId of Flintium/<udt_type>."""
    return system.tag.configure(
        basePath="[default]",
        tags=[{{
            "name": path.rsplit("/", 1)[-1],
            "tagType": "UdtInstance",
            "typeId": "Flintium/" + udt_type,
        }}],
        collisionPolicy="o",
    )


def alarm_active():
    """Return active alarms via system.alarm.queryStatus."""
    return [
        {{"path": str(a.getSource()), "active": a.isActive(), "ack": a.isAcked()}}
        for a in system.alarm.queryStatus().getDataset()
    ]


def alarm_ack(path):
    """Acknowledge an alarm by source path."""
    return system.alarm.acknowledge([path])


def plc_status(name):
    """Probe a device via system.device.listDevices and tag reads."""
    devices = system.device.listDevices()
    return [
        {{"name": str(d["Name"]), "status": str(d["Status"]), "type": str(d["Type"])}}
        for d in devices
        if name.lower() in str(d["Name"]).lower()
    ]


def gw_status():
    """Return gateway address + uptime info."""
    return {{
        "address": system.util.getGatewayAddress(),
        "version": system.util.getProductCode(),
    }}


def troubleshoot(issue):
    """Look up a diagnosis from the embedded knowledge base."""
    issue_lc = (issue or "").lower()
    for key, fix in TROUBLESHOOT_KB.items():
        if key in issue_lc:
            return {{"issue": issue, "diagnosis": fix}}
    return {{"diagnosis": "Topics: " + ", ".join(sorted(TROUBLESHOOT_KB.keys()))}}
'''


def render_tools_py(udts, udt_index, instance_index):
    """Render flintium/tools/code.py with embedded indexes."""
    udts_payload = [
        {
            "name": entry["name"],
            "parent": entry.get("parent"),
            "level": entry.get("level"),
            "group": entry.get("group"),
            "fieldCount": entry.get("fieldCount"),
            "resolved": entry.get("fieldCount"),
        }
        for entry in udt_index["udts"]
    ]
    insts_payload = [
        {"id": i["id"], "label": i["label"], "udt": i["udt"], "path": i["path"]}
        for i in instance_index["instances"]
    ]
    return TOOLS_PY.format(udt_index=udts_payload, instance_index=insts_payload)
